spring.web.resources.cache.period=0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

logging.level.org.springframework=DEBUG
logging.level.ws.mia=DEBUG